// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onStateHumidityChange();
void onStateMotorChange();

int stateHumidity;
bool stateMotor;

void initProperties(){

  ArduinoCloud.addProperty(stateHumidity, READWRITE, 5 * SECONDS, onStateHumidityChange);
  ArduinoCloud.addProperty(stateMotor, READWRITE, ON_CHANGE, onStateMotorChange);



}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
